[package]
name = "rust-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "1.3.49"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
serde = "1.0.148"